"""
AirTS-Forecast Project
Section 1.2: Pollution Data Gathering, Exploration, and Spectral Analysis
File: pollution_data_combined_pollutants.py
Author: Tiago TOLOCZKO ROSS

Description:
    Combined pollutant analysis and plotting module. Aggregates multiple
    pollutants from a target directory and generates comparative
    Power Spectral Density (PSD) periodograms.
"""
__author__ = "Tiago TOLOCZKO ROSS"
__email__ = "rosst@alunos.utfpr.edu.br"
__version__ = "1.0.1"

import logging
from pathlib import Path
from typing import Any, Tuple, Dict, Optional, Union

import pandas as pd
import matplotlib.pyplot as plt
import pollution_data_exp_core as pdp

def get_analysis_pollutants(
        data_directory: Union[Path, str],
        periodicity: str = "hourly",
        diff_order: int = 0,
        **kwargs: Any
) -> Dict[str, Tuple[pd.DataFrame, Union[pd.Series, Tuple[pd.Series, ...]]]]:
    """
    Iterates over a directory of CSV files, extracts metadata, and processes
    each pollutant dataset into an aggregated dictionary.

    Args:
        data_directory (Union[Path, str]): The target directory containing pollutant CSV files.
        periodicity (str): Target resampling frequency.
        diff_order (int): Order of differentiation to apply.
        **kwargs: Additional parameters passed to the resampling engine.

    Returns:
        Dict[str, Tuple]: A mapping of pollutant names to their processed DataFrames and Series.
    """
    analysis_pollutants = {}
    target_dir = Path(data_directory)

    if not target_dir.is_dir():
        logging.error(f"POLLUTANT_ITERATION: Target directory does not exist - {target_dir}")
        return analysis_pollutants

    for pollutant_file in target_dir.iterdir():
        if pollutant_file.suffix == ".csv":
            try:
                filename = pollutant_file.name
                meta = pdp.parse_pollution_metadata(filename)

                if not meta or 'pollutant' not in meta:
                    logging.warning(f"POLLUTANT_ITERATION: Skipped {pollutant_file.name} (Invalid/missing metadata).")
                    continue

                pollutant_name = meta['pollutant']
                logging.info(f"POLLUTANT_ITERATION: Processing dataset for {pollutant_name}...")

                processed_data = pdp.pollution_data_resampling(
                    pollutant_file,
                    periodicity=periodicity,
                    diff_order=diff_order,
                    **kwargs
                )

                analysis_pollutants[pollutant_name] = processed_data

            except Exception as e:
                logging.error(f"POLLUTANT_ITERATION: Critical failure processing {pollutant_file.name} - {e}")
                continue

    return analysis_pollutants


def export_series_to_parquet(
        data_dict: Dict[str, Tuple[pd.DataFrame, Union[pd.Series, Tuple[pd.Series, ...]]]],
        output_filepath: Union[Path, str],
        **kwargs: Any
) -> bool:
    """
    Extracts the processed time-series for each pollutant, aligns them into
    a single multi-column DataFrame, and exports the result to a Parquet file.

    Args:
        data_dict (Dict[str, Tuple]): The dictionary generated by `get_analysis_pollutants`.
        output_filepath (Union[Path, str]): The destination file path (should end in .parquet).
        **kwargs: Additional arguments passed to pandas.DataFrame.to_parquet()
                  (e.g., engine='pyarrow', compression='snappy').

    Returns:
        bool: True if the export was successful, False otherwise.
    """
    if not data_dict:
        logging.warning("PARQUET_EXPORT: No data provided. Aborting export.")
        return False

    series_collection = {}

    for pollutant_name, raw_data in data_dict.items():
        try:
            # Extract the processed pd.Series safely, accommodating both differentiated
            # tuples and standard Series outputs from the ingestion pipeline.
            if isinstance(raw_data, tuple):
                # raw_data[1] contains the Series or Tuple of Series
                extracted_data = raw_data[1]
                series = extracted_data[0] if isinstance(extracted_data, tuple) else extracted_data
            else:
                series = raw_data

            # Ensure the series is properly named so it becomes a valid column header
            series.name = pollutant_name
            series_collection[pollutant_name] = series

        except Exception as e:
            logging.error(f"PARQUET_EXPORT: Failed to extract series for {pollutant_name} - {e}")
            continue

    if not series_collection:
        logging.error("PARQUET_EXPORT: No valid series extracted. Aborting export.")
        return False

    try:
        # Concatenate all series along the columns (axis=1).
        # Pandas automatically aligns the data based on the DatetimeIndex.
        combined_df = pd.concat(series_collection.values(), axis=1, join="outer")

        # Convert the DatetimeIndex into a standard explicit column named 'Timestamp'
        combined_df = combined_df.rename_axis('timestamp').reset_index()

        # Validate and create parent directories if necessary
        target_path = Path(output_filepath)
        target_path.parent.mkdir(parents=True, exist_ok=True)

        # Set default efficient compression if not provided in kwargs
        compression = kwargs.get("compression", "snappy")
        engine = kwargs.get("engine", "pyarrow")

        # Write to Parquet
        logging.info(f"PARQUET_EXPORT: Writing {combined_df.shape} dataset to {target_path}...")
        combined_df.to_parquet(target_path, engine=engine, compression=compression)
        logging.info("PARQUET_EXPORT: Export completed successfully.")
        return True

    except ModuleNotFoundError:
        logging.error("PARQUET_EXPORT: Missing dependencies. Ensure 'pyarrow' or 'fastparquet' is installed.")
        return False
    except Exception as e:
        logging.error(f"PARQUET_EXPORT: Critical I/O failure during file write - {e}")
        return False


def visualize_multiple_spectra(
        data_dict: Dict[str, Union[pd.Series, Tuple[Any, pd.Series]]],
        top_k: int = 5,
        save_file: bool = False,
        title: str = None,
        **kwargs: Any
) -> Optional[plt.Figure]:
    """
    Generates a combined comparative Power Spectral Density (PSD) periodogram
    for multiple pollutants.

    Args:
        data_dict: Dictionary mapping pollutant names to their time-series data.
        top_k: Number of dominant periods to identify per pollutant.
        save_file (bool): Whether to save the combined PSD periodogram.
        **kwargs: Matplotlib styling parameters.

    Returns:
        Optional[plt.Figure]: The rendered comparative plot.
    """
    if not data_dict:
        return None

    fig, ax = plt.subplots(figsize=kwargs.get("figsize", (14, 7)))
    cmap = plt.get_cmap(kwargs.get("cmap", "tab10"))

    for idx, (pollutant_name, raw_data) in enumerate(data_dict.items()):
        color = cmap(idx % 10)

        # Safely extract the Series if the data structure is a tuple
        if isinstance(raw_data, tuple):
            series = raw_data[1][0] if isinstance(raw_data[1], tuple) else raw_data[1]
        else:
            series = raw_data

        periods, amplitudes, psd_summary = pdp.fourier_analysis(series, periodicity='hourly', top_k=top_k)

        ax.plot(periods, amplitudes, color=color, linewidth=1.5, label=pollutant_name, alpha=0.8)

        top_p = psd_summary.get("dominant_periods_raw", [])
        top_a = psd_summary.get("dominant_amplitudes", [])

        if top_p:
            ax.scatter(top_p, top_a, color=color, zorder=3, edgecolors='black', s=40)

            for i, (p, a) in enumerate(zip(top_p, top_a)):
                y_offset = 15 if i % 2 == 0 else -20
                ax.annotate(
                    f"{pollutant_name} (T={p})",
                    (p, a),
                    textcoords="offset points",
                    xytext=(5, y_offset),
                    ha='left',
                    va='center',
                    fontsize=8,
                    color='black',
                    arrowprops=dict(arrowstyle="->", color=color, alpha=0.7)
                )

    if not kwargs.get("force_linear_x", False):
        ax.set_xscale("log")

    if title is not None:
        ax.set_title(title, fontweight="bold")
    else:
        title=""
        ax.set_title(title, fontweight="bold")

    ax.set_xlabel("Period Length (Logarithmic scale)")
    ax.set_ylabel("Amplitude")
    ax.grid(True, which="both", linestyle="--", alpha=0.4)
    ax.legend(loc="upper right")

    fig.tight_layout()

    if save_file:
        # Unify folder and filename resolution safely using pathlib
        save_folder = Path(kwargs.get("save_folder", "./"))
        save_filename = kwargs.get("save_path", f"{title}.png")
        full_save_path = save_folder / save_filename

        dpi = kwargs.get("dpi", 300)

        try:
            full_save_path.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(full_save_path, bbox_inches="tight", dpi=dpi)
            logging.info(f"VISUALIZATION: Fourier spectrum successfully saved to {full_save_path}")
        except Exception as e:
            logging.error(f"VISUALIZATION_ERROR: I/O failure while saving figure to {full_save_path}. {e}")

    return fig


def main() -> None:
    """Execution orchestrator."""
    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

    datadir = Path(__file__).parent / "GEODAIR_POLLUTION_DATA"
    for file in datadir.iterdir():
        print(file)

    data_dict = get_analysis_pollutants(datadir, periodicity="hourly", apply_cleaning=False, diff_order=2)
    data_dict = get_analysis_pollutants(datadir, periodicity="hourly")

    if data_dict:
        # Export the consolidated data
        output_file = Path("outputs/consolidated_pollutants.parquet")
        export_series_to_parquet(data_dict, output_filepath=output_file)

    if data_dict:
        visualize_multiple_spectra(
            data_dict=data_dict,
            top_k=0,
            save_file=True,
            title="Comparative Spectral Analysis Periodogram second order",
            save_folder="./outputs"
        )
        plt.vlines([6, 12, 24], ymin=0, ymax=1.75, colors='black', alpha=.25,linestyles='dashed')
        plt.show()
    else:
        logging.warning("No data found to plot.")

if __name__ == "__main__":
    main()